export const productItems = [
    {
        img: './images/Rectangle_1751.png',
        name: 'WW90T754ABT, Pralka QuickDrive™, 9 kg, biała',
        capacity: 9,
        dimensions: '55 x 60 x 85 cm',
        functions: 'Drzwi AddWash™, Panel AI Control, Wyświetlacz elektroniczny',
        energyClass: 'A',
        price: 3299,
        payments: '53,31 zł x 60 rat',
    },
    {
        img: './images/Rectangle_1752.png',
        name: 'WW10T654DLH, Pralka EcoBubble™, 10,5 kg, biała',
        capacity: 10.5,
        dimensions: '55 x 60 x 85 cm',
        functions: 'Drzwi AddWash™, Silnik inwerterowy, Wyświetlacz elektroniczny',
        energyClass: 'B',
        price: 3199,
        payments: '53,31 zł x 60 rat',
    },    
    {
        img: './images/Rectangle_1752.png',
        name: 'WW90T654DLH, Pralka EcoBubble™,9 kg, biała',
        capacity: 9,
        dimensions: '55 x 60 x 85 cm',
        functions: 'Drzwi AddWash™, Panel AI Control, Silnik inwerterowy',
        energyClass: 'C',
        price: 2499,
        payments: '53,31 zł x 60 rat',
    },    
    {
        img: './images/Rectangle_1751.png',
        name: 'WW90T754ABT, Pralka QuickDrive™, 9 kg, biała',
        capacity: 9,
        dimensions: '55 x 60 x 85 cm',
        functions: 'Drzwi AddWash™, Panel AI Control, Wyświetlacz elektroniczny',
        energyClass: 'D',
        price: 3099,
        payments: '53,31 zł x 60 rat',
    },    
    {
        img: './images/Rectangle_1752.png',
        name: 'WW10T654DLH, Pralka EcoBubble™, 10,5 kg, biała',
        capacity: 10.5,
        dimensions: '55 x 60 x 85 cm',
        functions: 'Panel AI Control, Silnik inwerterowy, Wyświetlacz elektroniczny',
        energyClass: 'E',
        price: 3199,
        payments: '53,31 zł x 60 rat',
    },    
    {
        img: './images/Rectangle_1752.png',
        name: 'WW90T654DLH, Pralka EcoBubble™, 8 kg, biała',
        capacity: 8,
        dimensions: '55 x 60 x 85 cm',
        functions: 'Drzwi AddWash™, Panel AI Control, Silnik inwerterowy',
        energyClass: 'F',
        price: 3299,
        payments: '53,31 zł x 60 rat',
    },  
];